title: "MadingleyR"
description: "MadingleyR: R package for the Madingley Model"

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-cayman
