name: linux

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        R: [ '4.3.3' ]  
    name: MadingleyR ${{ matrix.R }} linux
    steps:
      - uses: actions/checkout@master
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
      - run: sudo apt-get install libc6
      - run: sudo apt-get install libcurl-dev
      # - run: sudo apt install libgdal-dev
      - run:  Rscript -e 'source("https://raw.githubusercontent.com/MadingleyR/MadingleyR/master/Tests/WorkFlowTest_v4.R")'
      
      
      
      
