name: windows

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        R: [ '4.3.3' ]  
    name: MadingleyR ${{ matrix.R }} windows
    steps:
      - uses: actions/checkout@master
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
          
      - name: Check package
        shell: Rscript {0}
        run: |
          source("https://raw.githubusercontent.com/MadingleyR/MadingleyR/master/Tests/WorkFlowTest_v4.R")
      
      
