name: windows

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        R: [ '3.5.3' ]  
    name: MadingleyR ${{ matrix.R }} windows
    steps:
      - uses: actions/checkout@master
      - name: Setup R
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.R }}
      - run: "R.exe" CMD BATCH C:\Users\myusername\Documents\R\Send_Outlook_Email.R
      
      
